parameters:
    aws.region: '%env(AWS_REGION)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Aws\S3\S3Client:
        arguments:
            -
                version: '2006-03-01'
                region: '%env(AWS_REGION)%'

    Aws\Sdk:
        arguments:
            -
                version: 'latest'
                region: '%aws.region%'
