parameters:
    aws.region: '%env(AWS_REGION)%'
    aws.media_convert.endpoint: '%env(AWS_MEDIA_CONVERT_ENDPOINT)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Aws\S3\S3Client:
        arguments:
            -
                version: '2006-03-01'
                region: '%aws.region%'

    Aws\MediaConvert\MediaConvertClient:
        -
            version: "2017-08-29"
            region: '%aws.region%'
            endpoint: '%aws.media_convert.endpoint%'

    Aws\Sdk:
        arguments:
            -
                version: 'latest'
                region: '%aws.region%'

    aws_public_api_key_authenticator:
        class: App\Core\Security\ApiKeyAuthenticator
        arguments:
            $apiKey: '%env(AWS_INTEGRATION_API_KEY)%'