parameters:
    locale: 'en'
    timezone: 'Europe/Luxembourg'
    app.env:  '%env(APP_ENV)%'
    routing.uuid_mask: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
    url_generator.base_host: "%env(FRONTEND_HOST)%"
    url_generator.templates:
        email_verification: '/users/email-verification/<token>'
        mailer_unsubscribe: '/users/email-unsubscribe'
        password_reset: '/users/password-reset/<token>'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Core\:
        resource: '../../src/Core/*'
        exclude: '../../src/Core/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Core\Controller\:
        resource: '../../src/Core/Controller'
        tags: ['controller.service_arguments']

    App\Core\ArgumentResolver\UuidValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 500 }

    App\Core\ParamConverter\QueryStringConverter:
        tags:
            - { name: request.param_converter, converter: querystring }

    _instanceof:
        App\Core\Messenger\ExternalJsonMessageSerializerInterface:
            tags: [ 'app.core.messenger.serializer' ]

    App\Core\Service\UrlGenerator:
        arguments:
            $frontendHost: '%url_generator.base_host%'
            $urls: '%url_generator.templates%'

    App\Core\Messenger\ExternalJsonMessageSerializer:
        arguments:
            $serializers: !tagged_iterator 'app.core.messenger.serializer'
