parameters:
    app.mailer.sender: moments@itinair.com
    app.mailer.from: 'Moments by Itinair <moments@itinair.com>'
    app.mailer.bcc:
        - balazs@itinair.com
#        - itinair@gonser.eu
    app.mailer.contact_recipient: balazs@itinair.com
    app.mailer.unsubscribe_url: '%env(MAILER_UNSUBSCRIBE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
