parameters:
    app.mailer.sender: balazs@itinair.com
    app.mailer.from: 'Itinair <balazs@itinair.com>'
    app.mailer.bcc: carlos+itinair@gonser.eu
    app.mailer.unsubscribe_url: '%env(MAILER_UNSUBSCRIBE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
