parameters:
    media_item.s3_bucket: '%env(MEDIA_ITEM_S3_BUCKET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Media\:
        resource: '../../src/Media/*'
        exclude: '../../src/Media/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Media\Controller\:
        resource: '../../src/Media/Controller'
        tags: ['controller.service_arguments']

    App\Media\Service\MediaItemManager:
        arguments:
            $s3BucketName: '%media_item.s3_bucket%'

    _instanceof:
        App\Core\Messenger\ExternalJsonMessageSerializerInterface:
            tags: [ 'app.core.messenger.serializer' ]

    App\Media\Service\MomentMediaManager:
        arguments:
            $s3BucketName: '%media_item.s3_bucket%'

    App\Media\Service\VideoMediaManager:
        arguments:
            $s3BucketName: '%media_item.s3_bucket%'

    App\Media\Service\AwsMediaConverterManager:
        arguments:
            $awsMediaConvertQueueArn: "%env(AWS_MEDIA_CONVERT_VIDEO_COMPOSE_QUEUE_ARN)%"
            $awsMediaConvertRoleArn: "%env(AWS_MEDIA_CONVERT_JOB_ROLE_ARN)%"
