parameters:
    media_item.s3_bucket: '%env(MEDIA_ITEM_S3_BUCKET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Media\:
        resource: '../../src/Media/*'
        exclude: '../../src/Media/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Media\Controller\:
        resource: '../../src/Media/Controller'
        tags: ['controller.service_arguments']

    App\Media\Service\MediaItemManager:
        class: App\Media\Service\MediaItemManager
        arguments:
            $s3BucketName: '%media_item.s3_bucket%'
