parameters:
    notification.email_override: 'balazs@itinair.com'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Notification\:
        resource: '../../src/Notification/*'
        exclude: '../../src/Notification/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Notification\Controller\:
        resource: '../../src/Notification/Controller'
        tags: ['controller.service_arguments']

    App\Notification\Service\Notifier:
        arguments:
            $notifierEmailOverride: '%notification.email_override%'
