doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'

    services:
        'Doctrine\Migrations\Version\MigrationFactory': 'App\Core\Doctrine\Migrations\MigrationFactory'

    organize_migrations: BY_YEAR_AND_MONTH
