framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'
            void: 'in-memory://'

            async_external:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_ASYNC_EXTERNAL)%'
                serializer: App\Core\Messenger\ExternalJsonMessageSerializer
                retry_strategy:
                    max_retries: 10
                    delay: 5000
                    multiplier: 1
                    max_delay: 0

            async_internal:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_ASYNC_INTERNAL)%'
                retry_strategy:
                    max_retries: 10
                    delay: 5000
                    multiplier: 1
                    max_delay: 0

        routing:
            'App\Core\Messenger\MessageBatch': async_internal

            'App\User\Message\UserCreatedEvent': async_internal
            'App\User\Message\UserUpdatedEvent': void
            'App\User\Message\UserFollowApprovedEvent': sync
            'App\User\Message\UserFollowUnfollowedEvent': sync

            'App\Media\Message\MediaItemUploadedEvent': async_internal
            'App\Media\Message\MomentMediaItemUploadedEvent': sync
            'App\Media\Message\MomentPublishedEvent': void
            'App\Media\Message\VideoCreatedEvent': async_internal
            'App\Media\Message\VideoDeletedEvent': async_internal
            'App\Media\Message\VideoMediaItemUploadedEvent': sync
            'App\Media\Message\VideoPublishedEvent': async_internal

            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async_internal
