security:
    enable_authenticator_manager: true

    password_hashers:
        App\User\Entity\User:
            id: 'App\User\PasswordHasher\MaintenancePasswordHasher'
#        App\User\Entity\User: 'auto'

    providers:
        users:
            entity:
                class: App\User\Entity\User

    firewalls:
        api_token_refresh:
            pattern:  ^/users/token/refresh
            stateless: true
            refresh_jwt:
                check_path: user_token_refresh

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        aws:
            pattern: ^/public/aws/
            stateless: true
            custom_authenticators:
                - 'aws_public_api_key_authenticator'

        user_login:
            pattern: ^/users/login$
            stateless: true
            provider: users
            custom_authenticators:
                - App\User\Security\MaintenancePasswordAuthenticator
            json_login:
                check_path: /users/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            pattern: ^/
            stateless: true
            provider: users
            jwt: ~

    access_control:
        - { path: ^/users/login$, roles: PUBLIC_ACCESS }
        - { path: ^/users/login/facebook$, roles: PUBLIC_ACCESS }
        - { path: ^/users/token/refresh$, roles: PUBLIC_ACCESS }
        - { path: ^/users/password-reset, roles: PUBLIC_ACCESS }
        - { path: ^/users/email-verification, roles: PUBLIC_ACCESS }
        - { path: ^/users$, roles: PUBLIC_ACCESS, methods: [POST] }

        - { path: ^/countries, roles: PUBLIC_ACCESS, methods: [ GET ] }
        - { path: ^/countries, roles: IS_AUTHENTICATED_FULLY, methods: [POST,PUT,DELETE] }
        - { path: ^/currencies, roles: PUBLIC_ACCESS, methods: [ GET ] }
        - { path: ^/currencies, roles: IS_AUTHENTICATED_FULLY, methods: [ POST,PUT,DELETE ] }
        - { path: ^/timezones, roles: PUBLIC_ACCESS, methods: [ GET ] }
        - { path: ^/timezones, roles: IS_AUTHENTICATED_FULLY, methods: [ POST,PUT,DELETE ] }

        - { path: ^/payments/stripe/checkout/callback, roles: PUBLIC_ACCESS, methods: [ POST ] }
        - { path: ^/payments/stripe/webhook, roles: PUBLIC_ACCESS, methods: [ POST ] }

        - { path: ^/public/aws, roles: IS_AUTHENTICATED_FULLY }

        - { path: ^/health, roles: PUBLIC_ACCESS }
        - { path: ^/doc, roles: PUBLIC_ACCESS }
        - { path: ^/demo, roles: PUBLIC_ACCESS }
        - { path: ^/public/, roles: PUBLIC_ACCESS }

        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
