version: '3.2'

services:
    php-fpm:
        container_name: itinair-php
        build: .
        image: itinair-php
        env_file: .env
        environment:
            ENABLE_XDEBUG: 1
            XDEBUG_MODE: "off"
        expose:
            - 9000
        volumes:
            - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - .:/app
    nginx:
        container_name: itinair-nginx
        image: nginx:alpine
        ports:
            - "80:80"
        links:
            - php-fpm
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/app

    db:
        container_name: itinair-db
        image: postgis/postgis:13-3.1-alpine
        env_file: .env
        ports:
            - "5432"
        volumes:
            - dbdata:/var/lib/postgresql/data

    rabbitmq:
        container_name: itinair-rabbitmq
        image: rabbitmq:3-alpine

volumes:
    dbdata:
