core_controllers:
    resource: '../../src/Core/Controller/'
    type: annotation

media_controllers:
    resource: '../../src/Media/Controller/'
    type: annotation

localization_controllers:
    resource: '../../src/Localization/Controller/'
    type: annotation

user_controllers:
    resource: '../../src/User/Controller/'
    type: annotation
