monolog:
    handlers:
        main:
            type:    stream
            handler: nested
            level:   debug
        nested:
            type:  stream
            path:  "php://stderr"
            level:   debug
            channels: ["!event", "!messenger", "!doctrine", "!console", "!deprecation"]
